version: '3.3'
services:
  mysql:
    image: mysql
    restart: always
    ports:
      - "4600:3306"
    expose:
      - "4600"
    environment:
      MYSQL_USER: "admin"
      MYSQL_ROOT_PASSWORD: "akanza"
      MYSQL_DATABASE: "node"
      MYSQL_PASSWORD: "admin"
    volumes:
      - ./data:/var/lib/mysql
    security_opt:
      - seccomp:unconfined
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=akanza